name: CI

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  checkov-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkov Scan
        uses: bridgecrewio/checkov-action@master

  tfsec-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install TFSec
        run: go install github.com/aquasecurity/tfsec/cmd/tfsec@latest

      - name: TFSec Scan
        run: tfsec

  terraform-azure:
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

      TF_VAR_public_key: ${{ secrets.TF_VAR_PUBLIC_KEY }}
      TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}

      terraform_directory: terraform/azure

    needs:
      - checkov-scan
      - tfsec-scan

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check -recursive
        working-directory: ${{ env.terraform_directory }}

      - name: Terraform Initialize
        run: terraform init
        working-directory: ${{ env.terraform_directory }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.terraform_directory }}

      - name: Terraform Plan
        run: terraform plan -out plan
        working-directory: ${{ env.terraform_directory }}

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve "plan"
        working-directory: ${{ env.terraform_directory }}
